language: python
python:
  - '3.6'
  - '2.7'
branches:
  only:
    - master
# before_install:
  # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # - git submodule update --init --recursive
  # - cp Jupyter-Quick-Setup-on-Mac/Jupyter_Setup.ipynb content/notebooks
  # - cp AWS-Jupyter-notebook-server/AWS_Jupyter_Notebook_Server.ipynb content/notebooks
  # - cp AWS-Jupyter-notebook-server/mappings.json content/notebooks
  # - cp Data-Viz-with-DiagrammeR-and-wordcloud/Data_Viz_DiagrammeR_and_wordcloud.ipynb content/notebooks
  # - cp taskorganizer/instacart_wc.png content/notebooks
  # - cp taskorganizer/instacart_wc.png content/2017
  # - cp taskorganizer/screenshot1.jpg content/2017
  # - cp taskorganizer/screenshot2.jpg content/2017
  # - cp taskorganizer/screenshot3.jpg content/2017
  # - cp taskorganizer/screenshot4.jpg content/2017
  # - cp taskorganizer/README.md content/2017/taskorganizer_README.md
install:
  - pip install -r requirements.txt
script:
- make publish
deploy:
  provider: pages
  local_dir: ./output
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
# env:
#   global:
#     secure: quTwfO5XJ9g5pLSNuxTDmh2oflgHc8LO2eIM1hq5QhXRwiTIgeevFH64emg4dSUfE9RUXO1jCKtjEDcRHSehEifN5LinNXZ5ZQsOLRUsJuziimmNT/apUG9efbknqV3vCQjHeoUEYmKyRIBENJzL1qzIty27+1lh0xs2mNhmzo+z6Og1cfQVdbzR4NMVzflqvSApin/7FYf4SI0INf0ighVB9CrTcByWN6rfJBYpToDVYPT8JQ7RkeGiJrf9RMaEETp7iFMvPOzlTDgpvvFAWzzrXWkQ7BSew9kqHXlzRL7aGxmYpDiCXlUwR4SOXU+vLXEQnuqb5K3z0yTDc+6dD2aZcQuTLCeUAPACz2aiRd6BcZclR0x6bMZcoksUf19zHZqpx9q5XU/6W/wmgzkPBmuCf2UO2G2Dv40rJeFoN63Pp67AXU4+0kFqnQ67DCYkSkzFMygGRi6X1908PF7dQeUoJdM0V5qQ4BFm49SvOJqBdjwCz2xjQ4FeeSjfv5b0g5wzZLwO1UFxGADgoPlyyw8ALiyl+hXs4o0dSbhUTFkDBXp2ezhqftO6w110zIXX5aQWE7ojADPHdZ8bsMb9ubaTdyD2J75Fb9Q7k4eiRh6xrL3YeqcsBCgj0wuB++3CAOk3hjVgkdrxCvmzQxfNvxPe2EBLgtGO0f3rnXIJzzo=
notifications:
  email:
    on_success: always
    on_failure: never
